### ISSUE TITLE
feat: tag Twitter handle

### ISSUE THREAD

**Issue by LayZeeDK** [this-is-learning/twitter-feed#6]
It would be awesome to tag the author's Twitter handle if it's linked in their DEV Community profile.

The RSS items only mention the author by name so we might have to visit the article's URL, then navigate to the author's page and finally scrape their Twitter handle from their Twitter profile URL.

Alternatively, we can consider using the Forem API, for example get article details by slug https://developers.forem.com/api

**Comment by mainawycliffe** [comment]
I was just going through the API docs, I think it's the way to go using the following https://developers.forem.com/api#operation/getArticleByPath

**Comment by LayZeeDK** [comment]
Ah yes, `@${response.user.twitter_username}`.

**Comment by mainawycliffe** [comment]
I will try and cook something up next week

Regards,
Maina Wycliffe
________________________________
